/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class usb_data_t implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[6][7]
     */
    public float chip1_data[][];

    /**
     * 6 motors, 7 commands each
     * LCM Type: float[6][7]
     */
    public float chip2_data[][];

    /**
     * 6 motors, 7 commands each
     * LCM Type: float[6][7]
     */
    public float chip3_data[][];

    /**
     * 6 motors, 7 commands each
     * LCM Type: int32_t[1]
     */
    public int motor_status[];

 
    public usb_data_t()
    {
        chip1_data = new float[6][7];
        chip2_data = new float[6][7];
        chip3_data = new float[6][7];
        motor_status = new int[1];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1e7c0535a7299ba5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.usb_data_t.class))
            return 0L;
 
        classes.add(lcmtypes.usb_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                outs.writeFloat(this.chip1_data[a][b]); 
            }
        }
 
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                outs.writeFloat(this.chip2_data[a][b]); 
            }
        }
 
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                outs.writeFloat(this.chip3_data[a][b]); 
            }
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeInt(this.motor_status[a]); 
        }
 
    }
 
    public usb_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public usb_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.usb_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.usb_data_t o = new lcmtypes.usb_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.chip1_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                this.chip1_data[a][b] = ins.readFloat();
            }
        }
 
        this.chip2_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                this.chip2_data[a][b] = ins.readFloat();
            }
        }
 
        this.chip3_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 7; b++) {
                this.chip3_data[a][b] = ins.readFloat();
            }
        }
 
        this.motor_status = new int[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.motor_status[a] = ins.readInt();
        }
 
    }
 
    public lcmtypes.usb_data_t copy()
    {
        lcmtypes.usb_data_t outobj = new lcmtypes.usb_data_t();
        outobj.chip1_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            System.arraycopy(this.chip1_data[a], 0, outobj.chip1_data[a], 0, 7);        }
 
        outobj.chip2_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            System.arraycopy(this.chip2_data[a], 0, outobj.chip2_data[a], 0, 7);        }
 
        outobj.chip3_data = new float[(int) 6][(int) 7];
        for (int a = 0; a < 6; a++) {
            System.arraycopy(this.chip3_data[a], 0, outobj.chip3_data[a], 0, 7);        }
 
        outobj.motor_status = new int[(int) 1];
        System.arraycopy(this.motor_status, 0, outobj.motor_status, 0, 1); 
        return outobj;
    }
 
}

