"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class usb_data_t(object):

    __slots__ = ["chip1_data", "chip2_data", "chip3_data", "motor_status"]

    __typenames__ = ["float", "float", "float", "int32_t"]

    __dimensions__ = [[6, 7], [6, 7], [6, 7], [1]]

    def __init__(self):
        self.chip1_data = [ [ 0.0 for dim1 in range(7) ] for dim0 in range(6) ]
        """ LCM Type: float[6][7] """
        self.chip2_data = [ [ 0.0 for dim1 in range(7) ] for dim0 in range(6) ]
        """
        6 motors, 7 commands each
        LCM Type: float[6][7]
        """

        self.chip3_data = [ [ 0.0 for dim1 in range(7) ] for dim0 in range(6) ]
        """
        6 motors, 7 commands each
        LCM Type: float[6][7]
        """

        self.motor_status = [ 0 for dim0 in range(1) ]
        """
        6 motors, 7 commands each
        LCM Type: int32_t[1]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(usb_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(6):
            buf.write(struct.pack('>7f', *self.chip1_data[i0][:7]))
        for i0 in range(6):
            buf.write(struct.pack('>7f', *self.chip2_data[i0][:7]))
        for i0 in range(6):
            buf.write(struct.pack('>7f', *self.chip3_data[i0][:7]))
        buf.write(struct.pack('>1i', *self.motor_status[:1]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != usb_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return usb_data_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = usb_data_t()
        self.chip1_data = []
        for i0 in range(6):
            self.chip1_data.append(struct.unpack('>7f', buf.read(28)))
        self.chip2_data = []
        for i0 in range(6):
            self.chip2_data.append(struct.unpack('>7f', buf.read(28)))
        self.chip3_data = []
        for i0 in range(6):
            self.chip3_data.append(struct.unpack('>7f', buf.read(28)))
        self.motor_status = struct.unpack('>1i', buf.read(4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if usb_data_t in parents: return 0
        tmphash = (0x1e7c0535a7299ba5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if usb_data_t._packed_fingerprint is None:
            usb_data_t._packed_fingerprint = struct.pack(">Q", usb_data_t._get_hash_recursive([]))
        return usb_data_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", usb_data_t._get_packed_fingerprint())[0]

